#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
      #  We are skipping `sshd` in the boot process because it takes forever to
      #  initialize the random number generator. Maybe
      #  https://daniel-lange.com/archives/152-Openssh-taking-minutes-to-become-available,-booting-takes-half-an-hour-...-because-your-server-waits-for-a-few-bytes-of-randomness.html
      #  will help if we upgrade the kernel.
      #
      #   # Create any missing keys
      #   /usr/bin/ssh-keygen -A

      #   printf "Starting sshd: "
      #   /usr/sbin/sshd
      #   touch /var/lock/sshd
        echo "OK"
}
stop() {
        printf "Stopping sshd: "
        killall sshd
        rm -f /var/lock/sshd
        echo "OK"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?